USE [master]
GO


CREATE DATABASE [LEA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LEA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LEA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LEA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LEA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LEA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LEA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LEA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LEA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LEA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LEA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LEA] SET ARITHABORT OFF 
GO

ALTER DATABASE [LEA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LEA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LEA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LEA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LEA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LEA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LEA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LEA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LEA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LEA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LEA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LEA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LEA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LEA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LEA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LEA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LEA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LEA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LEA] SET  MULTI_USER 
GO

ALTER DATABASE [LEA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LEA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LEA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LEA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LEA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LEA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LEA] SET  READ_WRITE 
GO


